import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#fafafa] p-5`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
